import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import { Toaster } from "react-hot-toast";
import { DevTools } from "jotai-devtools";
import Provider from "./components/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-500`}>
        <Provider key={"jotai"}>
          {/* <Toaster position="bottom-center" /> */}
          <div className="flex">
            <Sidebar />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
